apiVersion: v1
kind: Service
metadata:
  name: tanner-core-api-svc
  namespace: core
  labels:
    app: tanner-core-api-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP     
  selector:
    app: tanner-core-api
